site_name: Heavenz Documentation

site_url: https://heavenz.lk/docs

site_description: Sample description

copyright: GPL v2

nav:
- 'Introduction': 'index.md'
- 'Start': 'start.md'
- 'About': 'about.md'

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'teal'
  font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'

pages:
- 'index.md'
- 'start.md'
